baseURL = "https://drhmoosavi.github.io/"
locale = "en_US"
title = "Hossein Moosavi"
enableRobotsTXT = true
disableKinds = ["home"]

[permalinks]
  posts = "/blog/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  author = "Hossein Moosavi"
  description = "Translational cancer research, bioinformatics, and machine learning."
